name: Slash Command Dispatch
on:
    issue_comment:
        types: [created]

jobs:
    slashCommandDispatch:
        runs-on: ubuntu-latest
        environment: release
        steps:
            - uses: xt0rted/pull-request-comment-branch@653a7d5ca8bd91d3c5cb83286063314d0b063b8e # v1
              id: comment-branch
              continue-on-error: true

            - name: Generate app token
              id: app-token
              if: success() && steps.comment-branch.outputs.head_ref
              uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Slash Command Dispatch
              uses: peter-evans/slash-command-dispatch@f996d7b7aae9059759ac55e978cff76d91853301 # v3
              if: success() && steps.comment-branch.outputs.head_ref
              id: slash-command
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  commands: |
                      lockfiles
                  permission: write
                  issue-type: pull-request
                  dispatch-type: workflow
                  static-args: ref=${{ steps.comment-branch.outputs.head_ref }}
